- name: Ansible Copy Local to Remote
  hosts: dev_server:stage_server:prod_server
  become: true
  vars:
    src_path: "/var/lib/jenkins/workspace/app-cicd-pipeline/webapp/target/webapp.war"
    dest_path: "/var/lib/tomcat/webapps"  # Adjust this path to the parent directory
  tasks:
    - name: Copy the file to remote servers
      ansible.builtin.copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}/webapp.war"
        owner: ansadmin
        group: ansadmin
        mode: '0644'
      register: copy_result
